In [1]:
import numpy as np

In [2]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [4]:
np.zeros(shape=(4, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.ones(shape=(5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.random.seed(101)
arr = np.random.randint(0, 100, 10)
print(arr)
print(arr.max())
print(arr.argmax())
print(arr.argmin())
print(arr.mean())

[95 11 81 70 63 87 75  9 77 40]
95
0
7
60.8
